### ISSUE TITLE
Readme.md has grammar errors

### ISSUE THREAD

**Issue by emeruvia** [AT-Studio/ProductLineTracker2#2]
Fix your grammar errors in the Readme.md

> This program utilizes JavaFX to create a Production Line
Tracker for a fictitious company. The user has the ability to
add new products to a catalog, produce these items, `as well track `the production history. The program makes 
use of FXML` as as` well as MVC architecture to create code that is
both maintainable and easy to understand.

**Comment by AT-Studio** [comment]
Thanks dude!
